# Generated by Django 4.2 on 2023-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mission', models.CharField(max_length=200)),
                ('vision', models.CharField(max_length=200)),
                ('corevalue', models.CharField(max_length=200)),
                ('facebook_url', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
                ('linkedin_url', models.CharField(max_length=200)),
                ('instagram_url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
