# Generated by Django 4.2.1 on 2023-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_photo_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='occasion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
